---
- name: Create Nexus Systemd Unit file
  template:
    src: nexus.service.j2
    dest: /lib/systemd/system/nexus.service
    mode: 0644
  register: nexus_systemd

- name: Ensure Nexus started and enabled
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure VM Options
  template:
    src: nexus.vmoptions.j2
    dest: "{{ nexus_config_vmoptions_file_path }}"
  notify: Restart Nexus

- name: Wait until Nexus config is created
  wait_for:
    path: "{{ nexus_config_file_path }}"
    state: present

- name: Configure Nexus
  template:
    src: nexus.properties.j2
    dest: "{{ nexus_config_file_path }}"
  notify: Restart Nexus

- name: Install lsyncd (RedHat) (Optional)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/l/lsyncd-2.2.2-1.el7.x86_64.rpm
    state: present
  when:
    - ansible_os_family == "RedHat"
    - install_lsyncd is defined
    - install_lsyncd
