---
- name: Add Nexus Group
  ansible.builtin.group:
    name: "{{ nexus_group }}"

- name: Add Nexus User
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    shell: /bin/bash
    home: "{{ nexus_install_dir }}"
