---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint ../../etc
platforms:
  - name: ubuntu2004
    image: quay.io/ansible/ubuntu2004-test-container
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    exposed_ports:
     - 8081/tcp
    published_ports:
     - 0.0.0.0:8081:8081/tcp
    privilaged: true  
    pre_build_image: true

  # - name: debian9
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true
    
  # - name: debian10
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true

  # - name: centos7
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true

  # - name: centos8
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true

  # - name: rhel7
  #   image: "registry.access.redhat.com/ubi7/ubi-init"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true

  # - name: rhel8
  #   image: "registry.access.redhat.com/ubi8/ubi-init"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   exposed_ports:
  #    - 8081/tcp
  #   published_ports:
  #    - 0.0.0.0:8081:8081/tcp
  #   privileged: true
  #   pre_build_image: true
  #   capabilities:
  #     - SYS_ADMIN
  #   command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/
  playbook:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    destroy: destroy.yml
scenario:
  name: default
verifier:
  name: testinfra